### ISSUE TITLE
minibatch size when training

### ISSUE THREAD

**Issue by YoelShoshan** [Genentech/equifold#11]
Hi!

"A mini-batch size of 8 was used with 8 A100 GPUs in Pytorch’s Distributed Data Parallel mode"
does this mean that the total number of samples  seen per optimizer step is:

[mb on a single gpu] x [gpus # in distributed setting]

* 8 x 8 = 64
or
* 1 x 8 = 8

?

**Comment by jaekor91** [comment]
1 x 8 = 8 was used
