### ISSUE TITLE
CSV example

### ISSUE THREAD

**Issue by amorehead** [Genentech/equifold#5]
Hello! First off, I want to thank all of you at Prescient Design for making EquiFold open-source.

I had a quick question. In your `README.md`, you reference some example CSV files for inference. Would you be able to share those files as well?

e.g., `tests/data/inference_ab_input.csv`

**Comment by jaekor91** [comment]
Hi @amorehead! Thank you for trying it out! I pushed the examples files.

**Comment by amorehead** [comment]
Thanks!
