### ISSUE TITLE
Support for missing/masked residues?

### ISSUE THREAD

**Issue by amorehead** [Genentech/equifold#6]
Hello. I had a quick question about your sequence parsing logic.

Is it at all possible to mask certain residues' types with EquiFold? If so, what amino acid character should I use in my input sequence CSV files to represent the unknown amino acid type? e.g., "X" for unknown, "-" for unknown, etc.?

**Comment by jaekor91** [comment]
Currently, EquiFold model can handle only the 20 canonical amino acid types. Extending the model to handle the unknown residue type is one of our future research directions.

**Comment by amorehead** [comment]
Thanks for clarifying this for me! Great work all around!
